config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  root 'tweets#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  def new
    @tweet = Tweet.new
  end
  def create
    message = params[:tweet][:message]
    tdate = Time.current
    @tweet = Tweet.new(message: message, tdate: tdate)
    if @tweet.save
      flash[:notice] = 'route:1'
      redirect_to '/'
    else
      render 'new'
    end
  end
  def show
    @tweet = Tweet.find(params[:id])
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/'
  end
  def edit
    @tweet = Tweet.find(params[:id])
  end
  def update
    @tweet = Tweet.find(params[:id])
    message = params[:tweet][:message]
    tdate = Time.now
    @tweet.update(message: message, tdate: tdate)
    if @tweet.save
      flash[:notice] = 'route:1'
      redirect_to '/'
    else
      render 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Twitter</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
            <%= csrf_meta_tags %>
                <% @count = Tweet.count %>
</head>

<body>
    <div id="header">
        <p>
            <a href="/">
                <%= image_tag('logo.PNG') %>
            </a>
        </p>
        <nav>
            <ul>
                <%= yield :header %>
            </ul>
        </nav>
    </div>

    <div id="container">
        <div id="wrapper">
            <div id="boxC">
                ニュース(適当)</br>
                多田野光彦爆殺
            </div>

            <div id="boxB">
                <%= yield %>
            </div>

            <div id="boxD">
                <p>あなたの名前は</p>
                <h2><strong>※ログインセッションで実装</strong></h2>
                <p2>です</p2>
            </div>

            <div id="boxE">
                <font color=#ffffff>
                    <p>あなたのツイート数</p>
                </font>
                <font color=#ffffff>
                    <h2><strong><%= @count %></strong></h2>
                </font>
            </div>

        </div>
    </div>

</body>

</html>

app/views/tweets/_buttom.html.erb
<li><a href=<%= url %> class="square_btn"><%= title %></a></li>

app/views/tweets/_editform.html.erb
<%= form_for @tweet, url: {action: :update} do |t| %>
    <p>
        <%= t.label :message, 'さっき何してた？' %>
            <%= t.text_field :message %>
    </p>
    <%= t.submit '歴史壊変' %>
        <% end %>

app/views/tweets/_newform.html.erb
<%= form_for @tweet, url: {action: :create}, :html => {:class => 'form'} do |t| %>
    <p>
        <%= t.text_field :message ,:placeholder => "今何してる？"%>
    </p>
    <%= t.submit 'ツイート' %>
        <% end %>

app/views/tweets/edit.html.erb
<% content_for :header do %>
    <%= render :partial => "buttom", :locals => { title: "Back to the Future",url: root_path} %>
        <% end %>

            <% if @tweet.errors.present? %>
                <h1>エラーが有るぞくそが</h1>
                <ul>
                    <% @tweet.errors.full_messages.each do |msg| %>
                        <li>
                            <%= msg %>
                        </li>
                        <% end %>
                </ul>
                <% end %>

                    <%= render :partial => "editform" %>

app/views/tweets/index.html.erb
<% content_for :header do %>
    <%= render :partial => "buttom", :locals => { title: "ツイート",url: new_tweet_path} %>
        <% end %>

            <div id="slide">
                <ul>
                    <% @tweets.reverse_each do |tweet| %>
                        <li>
                            <strong><%= tweet.message %></strong></br>
                            <%= time_ago_in_words(tweet.tdate) %>
                                <%= "前" %>
                                    <%= link_to 'このツイート情報を表示', "/tweets/#{tweet.id}", :style=>"color:#778899;" %>
                        </li>
                        <% end %>
                </ul>
            </div>

app/views/tweets/new.html.erb
<% content_for :header do %>
    <%= render :partial => "buttom", :locals => { title: "戻る",url: root_path} %>
        <% end %>

            <% if @tweet.errors.present? %>
                <h1>エラーが有るぞくそが</h1>
                <ul>
                    <% @tweet.errors.full_messages.each do |msg| %>
                        <li>
                            <%= msg %>
                        </li>
                        <% end %>
                </ul>
                <% end %>

                    <%= render :partial => "newform" %>

app/views/tweets/show.html.erb
<% content_for :header do %>
    <%= render :partial => "buttom", :locals => { title: "Go back to Tire1",url: root_path} %>
        <% end %>

            <div id="show">
                <ul>
                    <h4>
                        <%= @tweet.message %>
                    </h4>
                    <%= time_ago_in_words(@tweet.tdate) %><%= "前" %>
                </ul>
                <%= link_to 'このツイートを編集', "/tweets/#{@tweet.id}/edit" %>
                    <%= link_to 'このツイートを削除', "/tweets/#{@tweet.id}", method: :delete %>
                <p></p>
            </div>